### ISSUE TITLE
Installation and runtime problems

### ISSUE THREAD

**Issue by guardiande** [f-zappa/check_mk_adsl_line#3] opened 2022-06-28 08:39 UTC
Hi @f-zappa

Thank you for this plugin.

I'm a total newbie when it comes to check_mk so please bear with me.

My setup
* Check_mk 2.1.0p3 running in Docker (podman)

I downloaded your mkp and copied it to the container and tried to install via `mkp -v install adsl_line-1.1.mkp`. This resulted in the following error:

```
Installing /omd/sites/test/var/check_mk/packages/adsl_line version 1.1.
File conflict: /omd/sites/cmk/local/lib/check_mk/base/plugins/agent_based/adsl_line.py already existing.
OMD[cmk]:~/downloads$ rm /omd/sites/cmk/local/lib/check_mk/base/plugins/agent_based/adsl_line.py /omd/sites/cmk/local/share/check_mk/checkman/adsl_line /omd/sites/cmk/local/share/check_mk/web/plugins/metrics/adsl_line.py /omd/sites/cmk/local/share/check_mk/web/plugins/wato/adsl_line.py /omd/sites/cmk/local/share/snmp/mibs/NAS.mib
OMD[cmk]:~/downloads$ mkp -v install adsl_line-1.1.mkp 
Installing /omd/sites/test/var/check_mk/packages/adsl_line version 1.1.
  Agent based plugins (Checks, Inventory):
    adsl_line.py
    Fixing permissions of /omd/sites/cmk/local/lib/check_mk/base/plugins/agent_based/adsl_line.py: 0640 -> 0644
  Checks' man pages:
    adsl_line
    Fixing permissions of /omd/sites/cmk/local/share/check_mk/checkman/adsl_line: 0640 -> 0644
  Legacy GUI extensions:
    plugins/metrics/adsl_line.py
    plugins/wato/adsl_line.py
    Fixing permissions of /omd/sites/cmk/local/share/check_mk/web/plugins/metrics/adsl_line.py: 0640 -> 0644
    Fixing permissions of /omd/sites/cmk/local/share/check_mk/web/plugins/wato/adsl_line.py: 0640 -> 0644
  SNMP MIBs:
    NAS.mib
    Fixing permissions of /omd/sites/cmk/local/share/snmp/mibs/NAS.mib: 0640 -> 0644
Traceback (most recent call last):
  File "/omd/sites/cmk/bin/check_mk", line 92, in <module>
    exit_status = modes.call(mode_name, mode_args, opts, args)
  File "/omd/sites/cmk/lib/python3/cmk/base/modes/__init__.py", line 69, in call
    return handler(*handler_args)
  File "/omd/sites/cmk/lib/python3/cmk/base/modes/check_mk.py", line 742, in mode_packaging
    cmk.base.packaging.do_packaging(args)
  File "/omd/sites/cmk/lib/python3/cmk/base/packaging.py", line 90, in do_packaging
    f(args)
  File "/omd/sites/cmk/lib/python3/cmk/base/packaging.py", line 300, in package_install
    packaging.install_by_path(path)
  File "/omd/sites/cmk/lib/python3/cmk/utils/packaging.py", line 398, in install_by_path
    return install(file_object=cast(BinaryIO, f))
  File "/omd/sites/cmk/lib/python3/cmk/utils/packaging.py", line 514, in install
    write_package_info(package)
  File "/omd/sites/cmk/lib/python3/cmk/utils/packaging.py", line 785, in write_package_info
    with pkg_info_path.open("w", encoding="utf-8") as f:
  File "/omd/sites/cmk/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/omd/sites/cmk/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/omd/sites/test/var/check_mk/packages/adsl_line'
```

I was able to fix this by changing the the name in the metadata of your package to `/omd/sites/cmk/var/check_mk/packages/adsl_line` . I guess there is a better way to fix this though :)

After the package is successfully installed I goto `Setup > Services > Service Monitoring Rules` and add a rule. This looks like this and seems to be broken to me:

![image](https://user-images.githubusercontent.com/4947715/176134390-86ca4ce3-3590-4db7-b5a7-6a18e72a902e.png)

**Comment by f-zappa** [comment] 2022-06-28 17:22
Hi guardiande,
I did set up a 2.1.0p4 test site for this (my production is still on 2.0.0p22, but I could not reproduce the installation failure. Not sure what happened in your installation.
The other error seems to be more important anyway. I found that I used a wrong type for the default values - this worked in 2.0, but it seems that 2.1 is more strict. Please find the new 1.2 version in the repository and let me know whether this works better!
Regards, Uli "f-zappa"

**Comment by guardiande** [comment] 2022-06-28 18:05
Thank you, for the quick response :)

Installation now works flawlessly.

Configuration is also possible. But I don't see any metrics. Keep in mind that I'm not check_mk savvy yet, so it could be a beginner's fault.

<img width="733" alt="image" src="https://user-images.githubusercontent.com/4947715/176251808-fb6f7cac-9dfe-48fa-8aab-40eb306e731c.png">

Any idea? What do I have to specify as the interface? The interface id from the OID?

**Comment by guardiande** [comment] 2022-06-28 18:31
Debugged a bit further...

Firstly - I changed the detect attribute to also match the Vigor 166. But only in the deployed plugin files. Maybe I have to repackage and/or restart cmk.

Looking at the SNMP walk I figure that the interface attribute should be set to `4`

<img width="285" alt="image" src="https://user-images.githubusercontent.com/4947715/176256391-16165bf0-63d3-45f9-acb1-b45af575dbde.png">

I don't see any metrics yet.

**Comment by guardiande** [comment] 2022-06-28 18:41
Working now :)

I think it was rediscovering the services. You can add Vigor 166 to the supported routers :)

**Comment by f-zappa** [comment] 2022-06-28 18:49
> I think it was rediscovering the services. You can add Vigor 166 to the supported routers :)

How did you change, like this?
    detect = matches(".1.3.6.1.2.1.1.1.0", ".*Vigor(130|165|166).*"),
No further changes were necessary?
If you can confirm, i'll repackage the whole thing.

**Comment by guardiande** [comment] 2022-06-28 18:58
Yep, this was it.

There is one minor flaw though which I guess is not related to your plugin: My upstream rate is zero. I guess this is a Vigor 166 bug. Is it read correctly in your setup?

**Comment by f-zappa** [comment] 2022-06-28 19:11
For me, it is showing upstream rate correctly.
![image](https://user-images.githubusercontent.com/43571251/176265888-835ec06a-ae2d-4644-8603-33010d9f0c17.png)

The value should be in 
`# 1.3.6.1.2.1.10.94.1.1.5.1.2 adslAturChanCurrTxRate (DSL router's Tx rate)`
which is empty in your screenshot :( Maybe the Vigor 166 is different in this point, although the other metrics match. Maybe you can find something in your snmpwalk output which matches the actual reading in the Vigor GUI?

Another idea: is your device set up as a router or as simple modem? I use the latter and maybe the behaviour depends on the configuration.

**Comment by guardiande** [comment] 2022-06-28 19:15
I also use it as a (more or less) dumb modem. There's no other oid matching the actual upstream rate (or something close). 

Here's another evidence that I'm not the only one though the user in question state that he was able to fix it: https://ubiquiti-networks-forum.de/board/thread/1531-monitoring-internetverbindung-dsl-mit-vigor-165/

Though I think it was only a browsing/mib issue.

BTW it could be helpful to mention to use interface 4 in the readme.

**Comment by f-zappa** [comment] 2022-06-28 20:14
OK, i created and uploaded the 1.2.1 version 

> Here's another evidence that I'm not the only one though the user in question state that he was able to fix it: https://ubiquiti-networks-forum.de/board/thread/1531-monitoring-internetverbindung-dsl-mit-vigor-165/

Similar setup, I also use an USG :)  But I'm not sure if this is the same effect, also they use a 165 model instead of your 166. 

Did you already check your firmware? Maybe this is already fixed in a newer version.

> BTW it could be helpful to mention to use interface 4 in the readme.

Added some words about it. Normally the interface no. should be autodiscovered, but if this doesn't work it might be good to know.

I'll close the ticket now, but please feel free to reopen if you have more suggestions for improvements or fixes.

**Closed as completed by f-zappa** 2022-06-28 20:14 UTC
